server:
  tomcat:
    accept-count: 200
    max-connections: 300
    connection-timeout: 10000
    uri-encoding: UTF-8
    background-processor-delay: 10
    accesslog:
      enabled: true
      directory: /home/ec2-user
      prefix: access_log
      suffix: .log
      pattern: "%h %l %u %t \"%r\" %s %b %D"
    threads:
      max: 200
      min-spare: 50
  compression:
    enabled: true
    mime-types: text/html,application/json
    min-response-size: 2048
  ssl:
    enabled: false
  port: 8080

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
